# Was being used for usb serial console, but using cp2102 usb to uart bridge instead, so disabling usb device stack for now
# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_DEVICE_VID=0x2FE3
# CONFIG_USB_DEVICE_PID=0x0004
# CONFIG_USB_DEVICE_PRODUCT="USB CDC-ACM serial console"

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NANOPB=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096